### ISSUE TITLE
Czech Parliamentary Meetings

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/resource-families-issues#1]
http://hdl.handle.net/11858/00-097C-0000-0005-CF9C-4

Issues:
- [ ] Unknown period

**Comment by stranak** [comment]
Updated description.

`The date of airing of a particular recording is encoded in the filename in the form SOUND_YYMMDD_*. Note that the recordings are usually aired in the early morning on the day following the actual Parliament session. If the recording is too long to fit in the broadcasting scheme, it is divided into several parts and aired on the consecutive days.`
