### ISSUE TITLE
English as a Foreign Language Corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#107]
http://urn.fi/urn:nbn:fi:lb-2014073010

- Metadata issues:
   - [ ] Unclear linguistic annotation
   - [ ] Unknown licence

**Comment by rueter** [comment]
An access URL would be good for assessment of corpus.

**Comment by tosaja** [comment]
This corpus is not yet available as it says UnderNegotiation.

**Comment by mmatthiesencsc** [comment]
@jakoble This corpus is indeed not yet available. Please remove from CRF list.

**Comment by jakoble** [comment]
Removed!
