### ISSUE TITLE
The Long Second Corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#108]
http://urn.fi/urn:nbn:fi:lb-2015031801

- Metadata issues:
   - [ ] Unknown size
   - [ ] Unclear linguistic annotation

**Comment by rueter** [comment]
It would be good to have an access address for assessment of the corpus.

**Comment by jakoble** [comment]
In the meta-share entry, it says that "The corpus will be made available in LAT (https://lat.csc.fi)." I assume making it available through LAT is still either in progress or was abandoned at one point?

**Comment by tosaja** [comment]
According to the metadata, the license is still under negotiation, so it should not be available yet.

**Comment by mmatthiesencsc** [comment]
@jakoble This corpus is indeed not yet available. Please remove from CRF list.

**Comment by jakoble** [comment]
Removed!
