### ISSUE TITLE
CEFLING Project Corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#110]
http://urn.fi/urn:nbn:fi:lb-20140730110

- Metadata issues:
   - [ ] Unknown size
   - [ ] Unclear linguistic annotation
   - [ ] Unknown licence

**Comment by rueter** [comment]
A link to the corpus would be good, so that annotations and size can be assessed.

**Comment by tosaja** [comment]
It is under negotiation, so it is not available yet. Should it be in VLO?

**Comment by mmatthiesencsc** [comment]
I think all corpora that are under Negotiation should be removed from the CRF or clearly marked as not yet available. We cannot add license or size information we don't have, @jakoble How is the process with these issues? Are you closing them?

**Comment by jakoble** [comment]
Hi Martin, you're right -- this is actually the plan for CRF listings going forward; that is, to no longer feature inaccessible tools or resources.

I'll be doing a more thorough review soon and close the remaining issues.
