### ISSUE TITLE
DIALUKI: Diagnosing reading and writing in a second or foreign language

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#111]
http://urn.fi/urn:nbn:fi:lb-20140730161

- [x] Not in VLO
- Metadata issue:
   - [ ] Unclear linguistic annotation

**Comment by rueter** [comment]
Meta-Share states this material will be made available in Korp, but there is no link to access.

**Comment by lennes** [comment]
@jakoble This resource is also still forthcoming, the license has been under negotiation for a long time. It is quite correctly not shown in VLO. This issue can be closed as well. Thanks!
