### ISSUE TITLE
Topling - Paths in Second Language Acquisition

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#112]
http://urn.fi/urn:nbn:fi:lb-20140730168

- Metadata issue: 
   - [ ] Unclear linguistic annotation

**Comment by eaxelson** [comment]
There is no access URN.

**Comment by eaxelson** [comment]
There are Swedish, Finnish and English subcorpora. The Finnish one contains annotation which is now marked in the metashare page (http://urn.fi/urn:nbn:fi:lb-2016111802). The Swedish and English ones (http://urn.fi/urn:nbn:fi:lb-2016111801 and http://urn.fi/urn:nbn:fi:lb-2016111803) have no annotation.
