### ISSUE TITLE
TAITO: Written and Oral Data of the TAITO-project

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#117]
http://urn.fi/urn:nbn:fi:lb-2014073035

- [ ] Not in VLO
- Metadata issues
   - [ ] Unknown size
   - [ ] Unclear linguistic annotation

**Comment by rueter** [comment]
Where is this material accessable?

**Comment by jakoble** [comment]
I also can't find an accessibility option anywhere (though I think it was accessible at one point)

**Comment by tosaja** [comment]
According to the metadata, the license is still under negotiation so it should not be accessible. Should it be in VLO?

**Comment by mmatthiesencsc** [comment]
It should not be in the VLO.

**Comment by jakoble** [comment]
Will be removed from the listings.
