### ISSUE TITLE
YKI National Certificates corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#118]
http://urn.fi/urn:nbn:fi:lb-20140730131

- Metadata issues:
   - [ ] Unknown size (in words/tokens, sentences, etc.)
   - [ ] Unclear linguistic annotation

**Comment by eaxelson** [comment]
The metadata says "Access location: http://yki-korpus.jyu.fi/", but I get "This site can’t be reached" when trying to access it.

**Comment by jakoble** [comment]
Yes, I get the same error, and can't find the corpus elsewhere.

**Comment by tosaja** [comment]
Are these still ongoing issues after moving away from Metashare?

**Comment by lennes** [comment]
This resource had licensing issues for many years, and the negotiations never succeeeded. Instead, the resource was replaced by another resource created in a specific research project (digitala-yki, https://urn.fi/urn:nbn:fi:lb-2023012629). Thus, this older metadata record needs to be removed (or replaced by a tombstone page; or perhaps with the digitala-yki resource group page http://urn.fi/urn:nbn:fi:lb-2024013001). 

@jakoble, could you please close this issue?
