### ISSUE TITLE
Sheffield Corpus of Chinese

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#123]
http://ota.ox.ac.uk/desc/2481

- metadata issues
   - [x] Unknown size

**Comment by eiamjw** [comment]
Plain text, no annotation.
How do you want to quantify size?
Link can be updated to http://hdl.handle.net/20.500.12024/2481

**Comment by jakoble** [comment]
I've updated the link. Any type of size is welcome; words are ideal, but you can also state number of documents.

**Comment by jakoble** [comment]
Size is now listed as: "148876", but no type. I assume it's words.
