### ISSUE TITLE
"PolDiLemma" Middle Polish Diachrone Lemmatized Corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#126]
http://hdl.handle.net/11858/00-246C-0000-0023-8C44-B

- metadata issue:
   - [ ]Unknown size

**Comment by jknappen** [comment]
Fixt in original CMDI metadata on our repository.

**Comment by twagoo** [comment]
@jknappen Hi Jörg, I have invited you to the resource families issues team within the CLARIN organisation on GitHub so that you can (self-)assign issues and/or close them if you deem them resolved.

**Comment by jknappen** [comment]
Ah, I see, I can now close the issue myself. Oriignal CMDI metadata are fixt.
