### ISSUE TITLE
Deutsches Textarchiv (DTA)

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#127]
http://hdl.handle.net/11372/LRT-172

- metadata issues:
   - [x] Unknown size
   - [x] Unclear linguistic annotation

**Comment by stranak** [comment]
Similar to issue #14, seems that this old record is outdated now and replaced by [a collection comprising many records](
https://vlo.clarin.eu/search?7-1.ILinkListener-searchContainer-searchResults-resultItem-7-resultItemDetails-searchResultCollectionLink&q=Deutsches+Textarchiv+%28DTA%29). 

Can somebody from CLARIN-D give us a handle to which we should send users who come using the handle of this old record?

**Comment by twagoo** [comment]
Perhaps @cthomasdta or @susannehaaf (currently on vacation) can help

**Comment by cthomasdta** [comment]
Yes, thank you, we will look into it this/next week.

**Comment by nolda** [comment]
There is a new DTA record in the [VLO](https://vlo.clarin.eu/record?docId=http_58__47__47_hdl.handle.net_47_21.11120_47_0000-0005-0ABA-F) and in the [BBAW repo](http://hdl.handle.net/21.11120/0000-0005-0ABA-F) superseding [LINDAT’s DTA record](http://hdl.handle.net/11372/LRT-172) and resolving those issues.
@stranak, could you please take LINDAT’s DTA record down?

**Comment by kosarko** [comment]
@nolda done. Might take a while before it disappears from the VLO.
