### ISSUE TITLE
Corpus of biblical text in Scots / John Kirk¸

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#128]
http://purl.ox.ac.uk/ota/1713

- Metadata issues:
   - [x] Unknown size
   - [x] Unclear linguistic annotation

**Comment by eiamjw** [comment]
No annotation
35506 words
Link can be updated to http://hdl.handle.net/20.500.12024/1713

**Comment by jakoble** [comment]
Thanks, updated!
