### ISSUE TITLE
Pamphlets of the American Revolution : [selections] / edited by Bernard Bailyn

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#129]
http://hdl.handle.net/20.500.12024/2021

- Metadata issues:
   - [ ] Unknown size

**Comment by jakoble** [comment]
File size says "431013", but no type is listed (e.g., word/token). I assume this is word size?

**Comment by eiamjw** [comment]
NB outdated handle prefix - this should be http://hdl.handle.net/20.500.14106/2021.

The size info has been updated, and now states 73953 tokens

**Comment by jakoble** [comment]
Thanks; info added to the backend.
