### ISSUE TITLE
Corpus of contemporary blogs

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#13]
http://hdl.handle.net/11858/00-097C-0000-000E-011B-8

- Metadata issues:
  - [x] Unknown period
  - [x] Unclear linguistic annotation

**Comment by stranak** [comment]
Hi, 

what would you consider clear information on the period and on the annotation?

**Period**: it is from 2011 and says "contemporary blogs". I realise it is not exact dating, but it is not irrelevant information.

**Annotation** seems to me to be rather clearly indicated. `Description` says:
> In order to make enough training data for machine learning, we split the corpus of contemporary text CBB.blog (1 million tokens) with annotators into senteces. Each file contains one hundredth of the whole corpus and all data were processed in parallel by two annotators.

Also the "Project URL" (`dc.source.uri`) attribute links to [more information including full annotation guidelines](https://nlp.fi.muni.cz/projekty/cocb/).

Any suggestion for improvement?

**Comment by TomazErjavec** [comment]
> Period: it is from 2011 and says "contemporary blogs". I realise it is not exact dating, but it is not irrelevant information.

Not that I am in any way an authority on this, but think Jakub, who spotted these mistakes, isn't either, so: I would write "from 2011" as this gives more info than just "contemporary". In fact this is exactly what I did with our flagged entries. And, yes, you can quibble on how much sense this makes, as we have e.g. forums from 2002 - 2016, but the distribution is heavily skewed towards later ones. Still, better something than (almost) nothing..

> Annotation seems to me to be rather clearly indicated.

I agree, I think Jakub didn't understand that it is only sentence breaks that are marked up, him being used to lemmatisation, tagging, etc.

**Comment by stranak** [comment]
I'll ask the submitters. I guess they didn't write it that way, because it was harvested 2011 but could have been written in period of several years up to 2011.

So maybe we add an explicit sentence into Description saying it is harvested / downloaded from web in 2011? Maybe saying what kind of webs? It is clear to Czech speakers from URLs, but doesn't actually say it explicitly in English.

**Comment by TomazErjavec** [comment]
> it was harvested 2011 but could have been written in period of several years up to 2011.

In our data we had the metadata on when e.g. a forum was posted, so we could write from-to, but, yes, in general the most you can do is write when it was harvested, as you note. That is still better than nothing, at least you know you won't find in it data from later.

> Maybe saying what kind of webs?

Can't hurt (except you, who have to spend time adding this:)

**Comment by stranak** [comment]
>In our data we had the metadata on when e.g. a forum was posted, so we could write from-to, but, yes, in general the most you can do is write when it was harvested, as you note. That is still better than nothing, at least you know you won't find in it data from later.

But I think that is exactly what `dc.date.issued` says, and it is filled-in as `2011`. The record was published in 2013, this "Date Issued" designates origin of the data. We don't have the "from" part.

**Comment by TomazErjavec** [comment]
> But I think that is exactly what dc.date.issued says

Wow, this would never occur to me - isn't this when the data was, well, issued, ie. made available (even if it wasn't then added to the repository)? That would be my interpretation anyway. Which is not necessarily (or even probably) when the crawl was terminated. In any case, I think it doesn't hurt to mention this in the description. My 2c...

**Comment by stranak** [comment]
You are probably right, lets make it clear. We'll put it into Description field.
