### ISSUE TITLE
The Lampeter Corpus of Early Modern English Tracts

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#132]
http://hdl.handle.net/20.500.12024/3193

- Metadata issues:
   - [ ] Unknown size

**Comment by jakoble** [comment]
File size says "50797916", but no type (e.g., words/tokens) is specified. I assume this is word size?

**Comment by eiamjw** [comment]
This has now been updated. The size is 1157586 tokens.

**Comment by jakoble** [comment]
Added to the backend, thanks!
