### ISSUE TITLE
Die Grenzboten (journal)

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#137]
http://www.deutschestextarchiv.de/doku/textquellen#grenzboten

- Metadata issue:
   - [x] Unknown licence

**Comment by cthomasdta** [comment]
Dear @jakoble , the Grenzboten are "gemeinfrei"/CC-0, cf. the teiHeader:
```
<availability>
<licence target="http://creativecommons.org/publicdomain/zero/1.0/">
<p>Dieses Werk ist gemeinfrei.</p>
</licence>
</availability>
```
Is that answer here in context sufficient for your task?

**Comment by twagoo** [comment]
Indeed, this information is present in the metadata. However it does not appear in the VLO which likely is a mapping issue.

The [curation module](https://curate.acdh.oeaw.ac.at/#!ResultView/instance/url/https://vlo.clarin.eu/data/clarin/results/cmdi/Berlin_Brandenburg_Academy_of_Sciences_and_Humanities_BBAW_/grenzboten_3.xml) tells us that the concept link on the 'availability/licence/@target' attribute is invalid. And ideed (from [expanded profile definition](https://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/profiles/clarin.eu:cr1:p_1381926654438/xml)):

```
                <CMD_Component name="availability" ConceptLink="http://hdl.handle.net/11459/CCR_C-2453_1f0c3ea5-7966-ae11-d3c6-448424d4e6e8" CardinalityMin="0" CardinalityMax="1">
                    <CMD_Component name="licence" ConceptLink="http://hdl.handle.net/11459/CCR_C-3800_12a79edd-0ffe-8d82-9831-45d125c54aee" CardinalityMin="1" CardinalityMax="1">
                        <AttributeList>
                            <Attribute><Name>target</Name><ConceptLink>http://hdl.handle.net/11459/CCR_C-6586_2c79d86a-  5a75-0890-d407-7d9cb86b9beb</ConceptLink><Type>anyURI</Type>
                                
                            </Attribute>
                        </AttributeList>
```

There's a stray space in the concept link (should be `http://hdl.handle.net/11459/CCR_C-6586_2c79d86a-5a75-0890-d407-7d9cb86b9beb`). Fixing this in the `publicationStmt` component (`clarin.eu:cr1:c_1381926654439`, currently with development status) should make the licence information be mapped correctly (or at least correctly mappable).
