### ISSUE TITLE
The Lancaster Newsbooks Corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#141]
http://purl.ox.ac.uk/ota/2531

- Metadata issues:
   - [x] Unknown size

**Comment by jakoble** [comment]
File size says 3001604 -- I assume this refers to words?

**Comment by eiamjw** [comment]
The wordcount is 999,248 - I'll update the metadata to reflect this.

**Comment by jakoble** [comment]
Thanks!
