### ISSUE TITLE
Finnish Folk Poetry

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#144]
http://urn.fi/urn:nbn:fi:lb-2014052712

- Metadata issue:
   - [x] Unclear linguistic annotation

**Comment by rueter** [comment]
No morphological annotation appears to be present in this multilingual corpus.
Words are given two additional forms: One without diacritics, and the other is a so-called normalized version. The normalized version appears to be merely a copy of the form without diacritics.
Perhaps, there should be information on  how each language form is to be normalized.
