### ISSUE TITLE
Classics Library of the National Library of Finland - Kielipankki version

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#149]
http://urn.fi/urn:nbn:fi:lb-2018051701

- [ ] Not in VLO
- Metadata issues:
   - [ ] Unknown size
   - [ ] Unclear linguistic annotation

**Comment by eaxelson** [comment]
There are two corpora:

* The Finnish sub-corpus of the Classics Library of the National Library of Finland - Kielipankki version (http://urn.fi/urn:nbn:fi:lb-201803281)
* The Swedish sub-corpus of the Classics Library of the National Library of Finland - Kielipankki version (http://urn.fi/urn:nbn:fi:lb-201804041)

Added annotation info to the metashare page of the Finnish sub-corpus. The Swedish one has not yet been published.
