### ISSUE TITLE
LITIS v.1

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#15]
http://hdl.handle.net/20.500.11821/11

- Metadata issues:
  - [x] Unclear linguistic annotation

**Comment by uandrius** [comment]
Hi, added dc.format="text/tab-separated-values". Hope this solves the issue.

**Comment by jakoble** [comment]
Thanks a lot! I take it that there's no linguistic annotation like PoS-tagging/lemmatization?

**Comment by uandrius** [comment]
That's right. This is a text corpus of comments with information of date, time, url, nick separated by tabs.

**Comment by jakoble** [comment]
Thanks!
