### ISSUE TITLE
Virtual Old Literary Finnish (VVKS) - Kielipankki Korp version

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#150]
http://urn.fi/urn:nbn:fi:lb-2017082101

- [ ] Not in VLO
- Metadata issues:
   - [x] Unknown size
   - [ ] Unclear linguistic annotation

**Comment by mmatthiesencsc** [comment]
Still not in VLO: https://vlo.clarin.eu/?5&q=urn:nbn:fi:lb-2017082101
Reason: The corpus is not yet published.
Size information has been added in original Metadata.

**Comment by jakoble** [comment]
Thanks, I'll add the size info on the resources families page as well
