### ISSUE TITLE
The Morpho-Syntactic Database of Mikael Agricola's Works

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#154]
http://urn.fi/urn:nbn:fi:lb-20140730170

- [x] Not in VLO

**Comment by mmatthiesencsc** [comment]
This can be closed: https://vlo.clarin.eu/record?q=mikael+agricola&docId=http_58__47__47_urn.fi_47_urn_58_nbn_58_fi_58_lb-20140730170
