### ISSUE TITLE
The Finnish Sub-corpus of the Newspaper and Periodical Corpus of the National Library of Finland, Kielipankki Version

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#155]
http://urn.fi/urn:nbn:fi:lb-2016050302

- [x] Not in VLO

**Comment by mmatthiesencsc** [comment]
Fixed: https://vlo.clarin.eu/record?4&count=3&docId=http_58__47__47_urn.fi_47_urn_58_nbn_58_fi_58_lb-2016050302&index=1&q=urn:nbn:fi:lb-2016050302

**Comment by jakoble** [comment]
Thanks!
