### ISSUE TITLE
Språkbanken's historical corpora

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#157]
https://spraakbanken.gu.se/korp/?mode=all_hist#?lang=en&stats_reduce=word&cqp=%5B%5D

- [x] Not in VLO (cf. one of the subcorpora, like "Gustav Vasas brevproduktion")

**Comment by arildm** [comment]
_Gustav Vasas brevproduktion_ is in VLO now, as [Gustav Vasa's letter production](https://vlo.clarin.eu/record/https_58__47__47_hdl.handle.net_47_10794_47_886_64_format_61_cmdi?7&count=1&index=0&q=vasabrev&tab=cmdi). I could find most of the others in the collection as well. At least one is, however, still missing: _Åkerbruk_.
