### ISSUE TITLE
Aalto University DSP Course Conversation Corpus 2013-2016, Downloadable Version

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#168]
http://urn.fi/urn:nbn:fi:lb-2017062133

Metadata issues:
- [ ] Unclear annotation, linguistic or otherwise

**Comment by eaxelson** [comment]
Unknown URN: urn:nbn:fi:lb-2017092133

**Comment by jakoble** [comment]
Ah, should be this one: http://urn.fi/urn:nbn:fi:lb-2017062133

**Comment by eaxelson** [comment]
Added annotation. @jakoble: I guess this issue can be closed?
