### ISSUE TITLE
Finnish Broadcast Corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#169]
http://urn.fi/urn:nbn:fi:lb-201403265

Metadata issue:
- [x] Unclear annotation, linguistic or otherwise

**Comment by eaxelson** [comment]
Added text info:

Annotation
Speech Annotation - Sound To Text Alignment
Speech Annotation - Orthographic Transcription

**Comment by eaxelson** [comment]
Added also approximation of text size:

Size
600 Utterances
3,500 Words
30 Files

**Comment by eaxelson** [comment]
@jakoble: I think this issue can be closed.
