### ISSUE TITLE
The Longitudinal Corpus of Finnish Spoken in Helsinki (1970s, 1990s and 2010s)

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#171]
http://urn.fi/urn:nbn:fi:lb-2014073041

Metadata issues:
- [ ] Unclear annotation, linguistic or otherwise

**Comment by eaxelson** [comment]
This version points to LAT service which is no longer in use. Use instead the downloadable version http://urn.fi/urn:nbn:fi:lb-201609142.
