### ISSUE TITLE
Gothenburg Dialogue Corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#188]
https://spraakbanken.gu.se/swe/resurs/gdc#tabs=information

- [x] Not in VLO

**Comment by arildm** [comment]
Hi! It is now in VLO: https://vlo.clarin.eu/record/https_58__47__47_hdl.handle.net_47_10794_47_240_64_format_61_cmdi?2&count=261&index=0&q=gdc
