### ISSUE TITLE
Szeged Treebank 2.0

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#191]
http://hdl.handle.net/11372/LRT-201

- [x] Missing licence

**Comment by maartenpt** [comment]
To download the versions of the Szeged Corpus and Szeged Treebank, you are obliged to fill and send a Licence Agreement (http://www.inf.u-szeged.hu/projectdirs/hlt/index_en.html)

**Comment by jakoble** [comment]
Thanks, I added this info to the Resource Family site, but as I see it, the fact that a licence is available for a resource should also be reflected in the repository entry; though I believe lindat-type repositories show licence information only for data downloadable from the repository itself.
