### ISSUE TITLE
CoMeRe repository

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#20]
https://hdl.handle.net/11403/comere

- Metadata issue:
  - [x] Unclear linguistic annotation

**Comment by christopheparisse** [comment]
Hello
Please can you tell me what do you mean about linguistic annotation?
If you could just give us a few example of "clear" linguistic annotation, then we would know what we can do.
Thank you.

**Comment by jakoble** [comment]
Hi Christophe,


Ideally, the description of the corpus should explicitly specify the levels of annotations (this seems to be missing for CoMeRe). This could be done by simply adding a line to the landing page like: "The corpora within this collection are PoS-tagged, lemmatised, marked for Named Entities", for instance.


Best,
Jakob


Univerza v Ljubljani
Filozofska fakulteta    asist. Jakob Lenardič


Oddelek za prevajalstvo / Department of translation

Filozofska fakulteta / Faculty of arts

Aškerčeva cesta 2, SI-1000 Ljubljana, Slovenija / Slovenia
T.: 241-1143
Jakob.Lenardic@ff.uni-lj.si<mailto:Jakob.Lenardic@ff.uni-lj.si>, www.ff.uni-lj.si<http://www.ff.uni-lj.si/>
[Univerza v Ljubljani]<http://www.uni-lj.si/>
________________________________

**Comment by christopheparisse** [comment]
Hi Jakob

Ok this is clear.
So we have to add this information on the Ortolang webpages.
In most cases that were tagged as problematic, the "unclear syntactic information" corresponds in fact to “no syntactic information”.
Is there a standard way to say this?
There are some specific cases. In Comere, the names are tagged, for example.
Is there information to add in the metadata formats, and if so, is there a reference for this format?
Thank you very much.

Best 
Christophe
