### ISSUE TITLE
North Saami Corpus (Literature) (UHLCS)

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#211]
http://urn.fi/urn:nbn:fi:lb-2014032620

- [x] Unclear annotation, linguistic or otherwise

**Comment by eaxelson** [comment]
The metashare page says:

"The corpus is available in Kielipankki - the Language Bank of Finland (taito-shell.csc.fi, access rights instructions: http://www.kielipankki.fi/access).

Location: /appl/kielipankki/mrc-uhlcs/multilingual-language-archive/uralic-lgs/finno-ugric-lgs/saami-lgs/north-saami"

Seems that after transfer from taito-shell server to puhti server the correct folder is "/appl/data/kielipankki/", but I get Permission denied as I don't have rights to access it.

**Comment by tosaja** [comment]
Is the "unclear annotation" still an existing issue after migrating from Metashare?

**Comment by mmatthiesencsc** [comment]
the path is fixed, this can be closed.

**Comment by lennes** [comment]
@jakoble, this corpus does not include any annotation, just the text files (original text files + files in utf8 encoding). We also fixed the file path. So, could you please close the issue?
