### ISSUE TITLE
Classics Library of the National Library of Finland - Kielipankki version

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#220]
http://urn.fi/urn:nbn:fi:lb-2018051701

- [x] Missing size
- [x] Unclear annotation

**Comment by eaxelson** [comment]
Added size "968 Texts".

**Comment by jakoble** [comment]
Thanks!

**Comment by tosaja** [comment]
Is the "unclear annotation" still an existing issue after migrating from Metashare?

**Comment by mmatthiesencsc** [comment]
@tosaja @eaxelson : This resource lacks a resource proxy entry, in other words it is not clear from where it can be accessed. Is this from the time we had corpus family pages in META-SHARE? Should this be removed and linked to https://www.kielipankki.fi/corpora/nlfcl/?

**Comment by lennes** [comment]
Yes, this is not an independent resource but an "umbrella" record, probably from META-SHARE as @mmatthiesencsc suggests, and nowadays replaced by our "resource group" pages. For now, I added a ResourceProxy (as type LandingPage) and provided the link to the resource page, for which this metadata record is actually a kind of alias. @mmatthiesencsc, is this a quick (and dirty) fix on the COMEDI side, or should we remove or hide the record completely?

@jakoble, I believe this issue should be closed. Can you take care of it, please? :)

**Comment by jakoble** [comment]
Thanks, Mietta, closed!
