### ISSUE TITLE
Parallel corpus newsletters IFT FR-GR

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#25]
http://hdl.grnet.gr/11500/AUTH-0000-0000-2557-5

- [x] Not in VLO
- Metadata issues:
  - [x] Unknown size (in tokens/words, sentences, etc.)
  - [ ] Unclear alignment/annotation

**Comment by jakoble** [comment]
Size is, at least according to the VLO, "3064.0 translationUnits"

**Comment by maria-gav** [comment]
Size also counted in kB (394 kilobytes)
