### ISSUE TITLE
@Philostei

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#270]
https://portal.clarin.nl/node/14367

- [x] Missing licence
- [x] Not in VLO

**Comment by JanOdijk** [comment]
This is actually more a description of a project. So it should not be in VLO, and 'license' is inapplicable. The software service resulting from this project (and some of its successors) is called PICCL and described elsewhere: https://vlo.clarin.eu/record/http_58__47__47_hdl.handle.net_47_10032_47_bb51fb884218b97cff95a518d9338ef5?1&q=piccl&index=0&count=1

**Comment by jakoble** [comment]
Thanks a lot, Jan! Will remove this from the tool list.
