### ISSUE TITLE
TiCClops

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#271]
https://portal.clarin.nl/node/14376

- [ ] Missing licence
- [ ] Not in VLO
- [ ] Broken links to web application:  http://ticclops.clarin.inl.nl/ticclops/ and http://ticclops.clarin.inl.nl/philostei/

**Comment by proycon** [comment]
This is a predecessor of PICCL (#276) and has been abandoned for a long time already.

**Comment by jakoble** [comment]
Thanks for the clarification!
