### ISSUE TITLE
NCHLT Tagger

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#283]
https://hdl.handle.net/20.500.12185/351

- [x] Does not specify NE categories

**Comment by fa-liabara** [comment]
Updated information in Description field:

Available in the Readme.txt - Input format: Utf8 text file containing running text. Output file format: The output file is a tab-delimited text file containing each token followed by its the assigned class. Output classes for named entity recognition: B-/I-ORG Organisation, B-/I-PER Person, B-/I-LOC Location, B-/I-MISC Miscellaneous, OUT Outside

**Comment by jakoble** [comment]
Thanks!
