### ISSUE TITLE
CTexTools 2

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#284]
https://hdl.handle.net/20.500.12185/480

- [x] NE categories are not specified

**Comment by fa-liabara** [comment]
Updated information in Description field:

Available in the Help file - Output classes for named entity recognition:
B-/I-ORG Organisation, B-/I-PER Person, B-/I-LOC Location, B-/I-MISC Miscellaneous, OUT Outside

**Comment by jakoble** [comment]
Thanks!
