### ISSUE TITLE
NCHLT Afrikaans Lemmatiser

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#298]
https://hdl.handle.net/20.500.12185/297@format=cmdi

- [x] Missing input and output info

**Comment by fa-liabara** [comment]
Updated information in Description field - Input format: Text data (encoding: UTF8 without BOM), one lowercase token per line. Output format: "Token tab Lemma".

**Comment by jakoble** [comment]
Thanks!
