### ISSUE TITLE
GLOSSOLOGIA

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#35]
http://hdl.grnet.gr/11500/UOA-0000-0000-257A-E

- [x] Not in VLO
- Metadata issues:
  - [x] Unknown size (in words/tokens, sentences, etc.)
  - [x] Unclear alignment/annotation

**Comment by jakoble** [comment]
167.0 sizeUnitarticle according to the VLO

**Comment by maria-gav** [comment]
counted in articles (not words, tokens, etc.)

**Comment by Kanella** [comment]
Glossologia has been renamed to Linguistics and is found in VLO [here](https://vlo.clarin.eu/record/http_58__47__47_hdl.handle.net_47_11500_47_UOA-0000-0000-257A-E_64_format_61_cmdi?1&q=linguistics&fqType=languageCode:or&fq=languageCode:code:ell&index=0&count=129).

**Comment by jakoble** [comment]
Thanks; I've amended this in our backend.
