### ISSUE TITLE
The DPC – Dutch Parallel Corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#353]
http://hdl.handle.net/10032/561929328633f6df581ea9ea1b12904a

- [x] Misssing licence

**Comment by bobboelhouwer** [comment]
Licensing information is available under 'GeneralInfo-DLU/Access/License'.

**Comment by jakoble** [comment]
Thanks! @bobboelhouwer, do you perhaps know why the VLO entry for this corpus (https://vlo.clarin.eu/record/http_58__47__47_hdl.handle.net_47_10032_47_d68c4ff787acfee15bff623561caf23b?5&q=The+DPC+%E2%80%93+Dutch+Parallel+Corpus&index=0&count=1) has availability defined as "unspecified"? This is what usually happens with missing licences, but the licence listed in the metadata i.e. "free for academic use by non-commercial organisation; user licence required" should map onto something like CLARIN ACA rather than unspecified.
