### ISSUE TITLE
Written corpus Gigafida 2.0

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#372]
https://viri.cjvt.si/gigafida/

- [ ] Not in VLO

**Comment by TomazErjavec** [comment]
The corpus description is now in CLARIN.SI: http://hdl.handle.net/11356/1320
And VLO knows about it too!
https://vlo.clarin.eu/record/https_58__47__47_hdl.handle.net_47_11356_47_1320_64_format_61_cmdi?1&count=24&docId=https_58__47__47_hdl.handle.net_47_11356_47_1320_64_format_61_cmdi&index=0&q=gigafida
So, I can finaly close this.
