### ISSUE TITLE
Written corpus Kres 1.0 

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#373]
http://www.korpus-kres.net/

- [ ] Not in VLO

**Comment by TomazErjavec** [comment]
The corpus is not in VLO, because it is not in the CLARIN.SI repository, so it cannot be in the VLO.
Or do I misunderstand something?

**Comment by jakoble** [comment]
No, you understand correctly! Perhaps in the case of this corpus the listed "issue" should be "not in CLARIN repo" rather than "not in VLO" (which indirectly implies the lack of repo entry); however, I still think that it'd be great to have  metadata records in CLARIN.SI for the full Gigafida & KAS corpora (pls recall that the full non-downloadable versions of these corpora are considered as "CLARIN corpora" in that both are available through noSke which is hosted by CLARIN.SI).

**Comment by TomazErjavec** [comment]
Gigafida has been added to CLARIN.SI, however, we will not add a description of KRES to CLARIN.SI, as this corpus is now very much out of date, and it does not look as if it will be updated. Also, contrary to what is written above, KRES is _not_ included in the CLARIN.SI concordancers. So, 1 exception to our policy of having only entries with data will be enough. Closing this issue.
