### ISSUE TITLE
finsentiment 

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#375]
https://www.kielipankki.fi/tools/demo/cgi-bin/predict/finsent.py

- [ ] Not in VLO
- [ ] Unknown licence

**Comment by tosaja** [comment]
This version does not exist anymore.

**Comment by mmatthiesencsc** [comment]
Consider https://www.kielipankki.fi/tools/demo/cgi-bin/finsent.py

**Comment by mmatthiesencsc** [comment]
But: This tool is meant as a demo, so no guarantees (as this issues shows). Do we really want to have it as part of the CRF?

**Comment by jakoble** [comment]
@mmatthiesencsc  For now I've changed the hyperlink to the working one. Do you feel the tool is too immature to be featured on CRF? It is accessible at least and to me looks like a good demo :).

I can close the ticket in any case though.

**Comment by mmatthiesencsc** [comment]
It is not mature enough, there are better tools available in hugging face. @traubert can give details.

**Comment by Traubert** [comment]
Well, it works and will likely work for the forseeable future, but it is very far from the state of the art. What is available on HuggingFace is BERT-based models trained by random people, so nothing that can really be used as an official resource, but very likely eg. https://huggingface.co/spaces/nisancoskun/nisancoskun-bert-finnish-sentiment-analysis-v2 would give more accurate results.

Really, we should do the same and train with our own handmade sentiment corpus, but it hasn't been a priority. In the meanwhile, the choices are to either keep the current one up or take it down. I don't mind leaving it up.

**Comment by lennes** [comment]
Was the license for 'finsent.py' set already, and if not, can @Traubert advise?

In any case, @jakoble, if you think the information is sufficient, please feel free to close this issue. :)

**Comment by mmatthiesencsc** [comment]
We use MIT, which can apply here.
