### ISSUE TITLE
links broken for SemiNER

### ISSUE THREAD

**Issue by kreetrapper** [clarin-eric/resource-families-issues#385]
The tool [SemiNER](https://github.com/clarin-eric/resource-families-html-generator/blob/7a54a2dc77b284e2313a3b90e7ad5ca121d376f0/resource_families/Tools/Named%20entity%20recognition/1-Tools%20for%20named%20entity%20recognition%20in%20the%20CLARIN%20infrastructure.csv#L17) has links for access and license that no longer work.

**Comment by jakoble** [comment]
Yep, this thing doesn't seem to exist anymore, so I'll remove it.
