### ISSUE TITLE
News in Finnish Sign Language

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#396]
http://urn.fi/urn:nbn:fi:lb-2014073012

- [ ] Missing size
- [ ] Unclear annotation
(though we note that the corpus seems not to have been released yet)

**Comment by tosaja** [comment]
Are these still existing issues after migrating from Metashare?

**Comment by lennes** [comment]
The metadata record exists for unknown reasons… The "access location" URL link actually points to the live website of Yle News in Finnish Sign Language, which is not a stable "resource" that we should be listing. We should (and we will) remove the metadata record from COMEDI as unwarranted.

@jakoble, please make sure this is not included in the Resource Families. Could you please close this issue, too?

**Comment by jakoble** [comment]
Removed it from the backend, so it should stop appearing from the online listings.
