### ISSUE TITLE
Consumer Information in Finnish Sign Language

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#398]
http://urn.fi/urn:nbn:fi:lb-2014073020

- [ ] Missing size
- [ ] Unclear annotation

**Comment by tosaja** [comment]
This seems to have a size and there is no annotation mentioned in the metadata anymore after migrating away from Metashare..

**Comment by lennes** [comment]
I cannot find any good reason why we should keep this metadata record. It points to an outdated website of a public entity (FInnish Competition and Consumer Authority), whose contents we have absolutely no control over. The content that was originally linked via the "access location" URL is no longer available, and we do not know of anyone who has actually used this as a language resource. @jakoble, this record should definitely not be listed in the Resource Families, so could you please take it out and close this issue? We will probably also remove the record from COMEDI, the current metadata platform we are using.

**Comment by jakoble** [comment]
I've removed it from the backend, so it should disappear from the online overviews in due course. Thanks, Mietta!
