### ISSUE TITLE
The Kipo Corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#399]
http://urn.fi/urn:nbn:fi:lb-2020112921

- [x] Unclear annotation

**Comment by tosaja** [comment]
I don't know if this an issue anymore after migrating away from Metashare.

**Comment by lennes** [comment]
I checked this and added information about the annotation of the videos. I think this is now done, if @jakoble approves :)

**Comment by jakoble** [comment]
Thanks, Mietta! Closing the issue.
