### ISSUE TITLE
Translations of the Bible and of the Church Manual into Finnish Sign Language

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#400]
http://urn.fi/urn:nbn:fi:lb-2014073029

- [ ] Missing size
- [ ] Unclear annotation

**Comment by tosaja** [comment]
This resource has been removed.

**Comment by mmatthiesencsc** [comment]
It should be removed from CRF. @tosaja at FIN-CLARIN we could use this page as tombstone: https://etsin.fairdata.fi/dataset/2dc0e087-0961-4151-9035-6aaf80c5f192

**Comment by jakoble** [comment]
Thanks, will be deleted.
