### ISSUE TITLE
broken Corpus URL in The English-Swedish Parallel Corpus

### ISSUE THREAD

**Issue by kreetrapper** [clarin-eric/resource-families-issues#406]
There is an entry at Språkbanken
https://spraakbanken.gu.se/en/resources/espc

which links to another place for more info:
https://sprak.gu.se/forskning/korpuslingvistik/korpusar-vid-spl/espc

The latter one is broken

**Comment by jakoble** [comment]
Thanks, replaced the link with the latter working one and added a note specifying that the corpus is not (and never was) available.
