### ISSUE TITLE
VGT records

### ISSUE THREAD

**Issue by VincentCCL** [clarin-eric/resource-families-issues#412]
VGT records should also have Flemish Sign Language and Vlaamse Gebarentaal as their languages, so they can be found when looking by language selection

**Comment by kreetrapper** [comment]
As far as I can see, all VGT entries have "Flemish Sign Language (VGT)" listed as a language. I would not like to list the same language in multiple ways (e.g. also listing "Vlaamse Gebarentaal" as you suggest). We are planning to switch to using ISO-codes (instead of language names) which, I think, would solve this issue.

**Comment by VincentCCL** [comment]
As far as I know now this is treated inconsistently. When looking for Flemish Sign Language I get one hit. When searching for VGT (in the general task bar), I get at least three hits which I don't get otherwise. While ISO codes may solve the problem in the background, these ISO codes for sign languages are very uncommon and not used by the sign language communities, so they should be converted to human-readable forms.
Cf. https://vlo.clarin.eu/?1&q=vgt

**Comment by kreetrapper** [comment]
Just to avoid confusion. Are you talking about the Sign Language Resource Family (as implied by the issue being in this git repo) or about the VLO? My comment was only about the Resource Family.
While the Families are curated by us, the VLO is fed from all the various CLARIN centres and the inconsistency is mostly due to these very heterogeneous sources.

**Comment by VincentCCL** [comment]
I was talking about the VLO. Apologies.

kind regards,

v.

On 30/06/2023 10:18, alekoe wrote:

> Just to avoid confusion. Are you talking about the Sign Language 
> Resource Family (as implied by the issue being in this git repo) or 
> about the VLO? My comment was only about the Resource Family.
> While the Families are curated by us, the VLO is fed from all the 
> various CLARIN centres and the inconsistency is mostly due to these 
> very heterogeneous sources.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***> 
> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", 
> "potentialAction": { ***@***.***": "ViewAction", "target": 
> "https://github.com/clarin-eric/resource-families-issues/issues/412#issuecomment-1614302431", 
> "url": 
> "https://github.com/clarin-eric/resource-families-issues/issues/412#issuecomment-1614302431", 
> "name": "View Issue" }, "description": "View this Issue on GitHub", 
> "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": 
> "https://github.com" } } ]


Links:
------
[1] 
https://github.com/clarin-eric/resource-families-issues/issues/412#issuecomment-1614302431
[2]

**Comment by twagoo** [comment]
Thanks @VincentCCL for reporting this! As this issue relates not to the resource families directly but rather to (a lack of) harmonisation in the metadata across centres, the information should probably be "rerouted" - and this issue closed.

I'll leave the closing of the issue up to @kreetrapper but before that let me summarise my interpretation of the situation for the record.

Among the search results for `vgt` in the VLO, we currently have
* [4 records](https://vlo.clarin.eu/search?q=vgt&fqType=dataProvider:or&fq=dataProvider:Instituut+voor+de+Nederlandse+Taal) from INT
* [17 records](https://vlo.clarin.eu/search?q=vgt&fqType=dataProvider:or&fq=dataProvider:MPI+for+Psycholinguistics) from MPI-PL

... as well as [1 record](https://vlo.clarin.eu/record/oai_58_www.ldc.upenn.edu_58_LDC2020T17?q=vgt&fqType=dataProvider:or&fq=dataProvider:Other) from another provider that is not related to Flemish Sign Language at all (also not represented as such, so not an issue in terms of this query).

Out of the [21 'actual' matches](https://vlo.clarin.eu/search?q=vgt+-dataProvider:Other), [5 records](https://vlo.clarin.eu/search?q=vgt+-dataProvider:Other&fqType=languageCode:or&fq=languageCode:code:vgt) use the language code 'VGT'. 

The [remaining records](https://vlo.clarin.eu/search?q=vgt+-dataProvider:Other+-languageCode:code:vgt) include:
* [1 record](https://vlo.clarin.eu/record/http_58__47__47_hdl.handle.net_47_10032_47_793279f04954e3c055dc28f5a9512067?q=vgt+-dataProvider:Other+-languageCode:code:vgt) from INT ("Hotel Review Corpus in Nederlandse Gebarentaal")
* [15 records](https://vlo.clarin.eu/search?q=vgt+-dataProvider:Other+-languageCode:code:vgt&fqType=dataProvider:or&fq=dataProvider:MPI+for+Psycholinguistics) from the MPI

I'll get in touch with the providers, as these all look like issues that can and should be addressed on their end.

Hope this helps!

P.S. this makes me realise that we need to find a  new platform to document and trace metadata issues, now that our Trac system has been deprecated.
