### ISSUE TITLE
Handle for BNC

### ISSUE THREAD

**Issue by eiamjw** [clarin-eric/resource-families-issues#413]
The main link to the British National Corpus in the Reference Corpora Resource Family needs updating to http://hdl.handle.net/20.500.14106/2554 .

In fact, all handles for OTA resources in the Resource Families need updating from 20.500.12024  to 20.500.14106

**Comment by kreetrapper** [comment]
Has been fixed with https://github.com/clarin-eric/resource-families-html-generator/commit/d11fe981574fab583168a7410d238b208f8b88a8
