### ISSUE TITLE
English-Urdu Religious Parallel Corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#49]
https://hdl.handle.net/11234/1-2582

- Metadata issue: 
  - [x] Unknown size

**Comment by stranak** [comment]
corrected, 14371 sentences

**Comment by twagoo** [comment]
@stranak I have invited you to the resource families issues team within the CLARIN organisation on GitHub so that you can (self-)assign issues and/or close them if you deem them resolved.
