### ISSUE TITLE
Hellenic Parliament Minutes 

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/resource-families-issues#6]
http://hdl.grnet.gr/11500/AEGEAN-0000-0000-2545-9

- [x] Not in VLO
- Metadata issues:
  - [ ] Unclear linguistic annotation

**Comment by dietervu** [comment]
In May 2019 the PID was not resolving anymore. Feedback from Maria Gavrilidou:

> The University of the Aegean (hosting this resource) have decided to unify in one single resource all datasets containing Minutes of Parliamentary Discussions (previously separately listed). The new link is hdl.grnet.gr/11500/AEGEAN-0000-0000-57FA-5. 
The old entries have been deleted from the catalog - this is  the reason they are not found. 

This would still require a tombstone page to be in place.

**Comment by maria-gav** [comment]
The hosting repo have been informed. A global solution for all such cases will be put in place.

**Comment by jakoble** [comment]
Annotation description is vague i.e. "Domain-specific annotation type"

**Comment by Kanella** [comment]
The University of the Aegean has created two resources (both found in the VLO as well):

- Hellenic Parliament Minutes (1989-1994, 1996-2021), http://hdl.handle.net/11500/CLARIN-EL-0000-0000-61AF-E
- Hellenic Parliament Minutes (1989-1994, 1997-2018), http://hdl.handle.net/11500/AEGEAN-0000-0000-57FA-5

Both are downloadable.
Old resources have been removed (unpublished) from the CLARIN:EL repository.
