### ISSUE TITLE
The Newspaper and Periodical OCR Corpus of the National Library of Finland (1771-1874) •	

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#81]
http://urn.fi/urn:nbn:fi:lb-201505112

- Metadata issues:
  - [ ] Unknown size
  - [ ] Unclear linguistic annotation

**Comment by rueter** [comment]
The .zip file download appears to be over 13 Gs. Is there any place on line where it can be accessed?

**Comment by twagoo** [comment]
> The .zip file download appears to be over 13 Gs. Is there any place on line where it can be accessed?

I have not checked in detail whether these completely overlap, but the newspapers provided by the National Library of Finland are [included in Europeana Newspapers](https://www.europeana.eu/nl/collections/topic/18-newspapers?page=1&qf=COUNTRY%3A%22Finland%22&view=grid&api=fulltext). The library also has [its own interactive interface](https://digi.kansalliskirjasto.fi/collections?id=82). Could be worth adding or mentioning these links somewhere.

**Comment by eaxelson** [comment]
Added the following to the metashare page (http://urn.fi/urn:nbn:fi:lb-2015051201):

"Size: 69,861 Files"
"Annotation Other Format: alto v1.2".
