### ISSUE TITLE
Corpora of Newspaper Texts

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#82]
http://metashare.elda.org/repository/browse/corpora-of-newspaper-texts/ba2fa776fccc11e18b49005056be118ec8894201fa444962adb2b25868c5c4f5/

- Metadata issue:
  - [ ] Unclear linguistic annotation

**Comment by tosaja** [comment]
What does "Unclear linguistic annotation" mean?

**Comment by mmatthiesencsc** [comment]
On top of that the link links to outdated metadata. Here's the right one: http://urn.fi/urn:nbn:fi:lb-20140730175
Some negotiations stall, which is not nice, but that is the reason we don't export such resources to the VLO. It is unclear to me how they ended up in the CRF.

**Comment by jakoble** [comment]
Thanks, Martin, will be removed from the listings.
