### ISSUE TITLE
Morgonbris

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#93]
https://spraakbanken.gu.se/eng/resource/ub-kvt-morgonbris

- [x] Not in VLO

**Comment by arildm** [comment]
It's here: https://vlo.clarin.eu/record/https_58__47__47_hdl.handle.net_47_10794_47_876_64_format_61_cmdi?20&count=1&index=0&q=morgonbris

**Comment by arildm** [comment]
Sorry – maybe instead of spamming these issues, I should point out that we recently batch-imported most of our resources to the repo exposed to VLO. That should have resolved most of [the SWE-CLARIN-related issues](https://github.com/clarin-eric/resource-families-issues/labels/SWE-CLARIN).

**Comment by jakoble** [comment]
Thanks a lot! I'll close all of these.
