### ISSUE TITLE
British Academic Written English Corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#95]
http://hdl.handle.net/20.500.12024/2539

- Metadata issue:
  - [ ] Unclear linguistic annotation

**Comment by eiamjw** [comment]
The description states: "In 2022 tagged versions of the files, with part-of-speech and constituency annotations, were added by Philip Durrant of the University of Exeter. The annotated corpus is available in three versions, one (in directory 'conll') is the original output from the Stanford Core NLP parser; one ('csv') is a slightly edited version in .csv format; a third ('csv_categorized') is the .csv files organized by discipline and year group."

**Comment by jakoble** [comment]
Thanks, added this info to the backend.
