### ISSUE TITLE
ICLE International Corpus of Learner English

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#96]
http://hdl.handle.net/11372/LRT-859

- Metadata issues:
   - [x] Unclear linguistic annotation
   - [x] Unknown licence

**Comment by stranak** [comment]
Again one old "LRT Inventory record, it seems.
Project page link goes to "Page non trouvée". Correct link seems to be https://uclouvain.be/en/research-institutes/ilc/cecl/icle.html
Principal author is sylviane.granger@uclouvain.be 

There is a newer version of the data: https://uclouvain.be/en/research-institutes/ilc/cecl/iclev2-cd-rom-frequently-asked-questions.html#ICLEv2
License is clearly closed (there is a link to order a CD-ROM), but information on annotation is online: https://uclouvain.be/en/research-institutes/ilc/cecl/iclev2-cd-rom-frequently-asked-questions.html

We can remove the record, or update it to the new metadata ... @dietervu, you are the LRT Inventory co-editor. What do you think?
