### ISSUE TITLE
The Uppsala Student English corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#97]
http://hdl.handle.net/20.500.12024/2457

- Metadata issues:
   - [ ] Unclear linguistic annotation

**Comment by eiamjw** [comment]
No annotation. Should this be reflected in the metadata?

**Comment by jakoble** [comment]
We believe that info about the lack of annotation should indeed be made explicit as good practice. I'm closing the issue in any case. Thanks, Martin!
