### ISSUE TITLE
Testipiste Corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#99]
http://urn.fi/urn:nbn:fi:lb-2017020701

- [ ] Not in VLO
- Metadata issue:
   - [ ] Unclear linguistic annotation

**Comment by rueter** [comment]
A URN would be good for accessing this material.

**Comment by tosaja** [comment]
This resource is not yet accessible.

**Comment by mmatthiesencsc** [comment]
This is not a bug, but a feature. We don't export inaccessible resources to the VLO.

**Comment by jakoble** [comment]
Thanks, Martin. Issue closed -- we will soon stop featuring in CRF all the inaccessible resources.
